spring: 
 activate:
  on-profile: "prod"
 build:
   version: "1.0"
accounts:
   message: "Welcome to EasyBank accounts related local Apis"
   contactDetails: 
      name: "Praveen Kumbar"
      email: "praveen@gmail.com"
   onCallSupport:
        - 9632070931
        - 9000000001
      